name: tweet-release

on:
  release:
    types: [published]

jobs:
  tweet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send Tweet
        uses: noweh/post-tweet-v2-action@v1.0
        with:
          message: |
            📢 New Release: ${{ github.event.repository.name }} ${{ github.event.release.tag_name }} has been released. 🚀
            📝 Release Notes: ${{ github.event.release.html_url }}
            - Notes: ${{ github.event.release.body }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
